CREATE TABLE IF NOT EXISTS some_table (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    test VARCHAR(30)
);
INSERT INTO some_table (test) VALUES ('BLAH');
CREATE TABLE IF NOT EXISTS mytest (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    number INTEGER DEFAULT 0,
    big_number DECIMAL DEFAULT 0,
    name VARCHAR(30)
);