-- sqlite
CREATE TABLE IF NOT EXISTS account (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(45) NOT NULL UNIQUE,
    session_key VARCHAR(45),
    password_hash VARCHAR(255),
    verifier VARCHAR(255),
    salt VARCHAR(255),
    access_level INTEGER NOT NULL DEFAULT 0,
    banned INTEGER NOT NULL DEFAULT 0,
    last_ip VARCHAR(15),
    last_login timestamp
);

CREATE TABLE IF NOT EXISTS ip_banned (
    ip VARCHAR(15) PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS realm (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(45) NOT NULL,
    address VARCHAR(45) NOT NULL,
    port INTEGER NOT NULL,
    type INTEGER NOT NULL DEFAULT 0,
    state INTEGER NOT NULL DEFAULT 0,
    flags INTEGER NOT NULL DEFAULT 0
)
